# Generated by Django 4.1.4 on 2023-02-04 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizes"},
        ),
    ]
